[package]
name = "nerf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dfdx = "0.10.0"
vecmath = "1.0.0"
rand = "0.8.5"
concat-arrays = "0.1.2"
